TEMPLATE = subdirs

CONFIG += ordered
SUBDIRS += "ACL"
SUBDIRS += "WCL"
SUBDIRS += "GCL"
SUBDIRS += "MCL"
SUBDIRS += "PCL"
SUBDIRS += "SCL"
SUBDIRS += "QCL"
SUBDIRS += "SOFA"
SUBDIRS += "qtservice"
SUBDIRS += "WSd"
